export const ENV_VARS = {
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  SUPABASE_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  SUPABASE_SECRET: process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE ?? "",
  PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID ?? "",
  PRIVY_APP_SECRET: process.env.NEXT_PUBLIC_PRIVY_APP_SECRET ?? "",
};
